name: Acessar Interface macOS 15

on:
  workflow_dispatch:

jobs:
  macos-desktop:
    runs-on: macos-15

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Senha do Usuário no macOS
        run: |
          # Altera a senha do usuário runner usando o dscl nativo do macOS
          sudo dscl . -passwd /Users/runner 123456
          
          # Ativa o serviço de Screen Sharing / VNC nativo
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on \
            -clientopts -setvnclegacy -vnclegacy yes \
            -clientopts -setvncpw -vncpw 123456 \
            -restart -agent -privs -all

      - name: Instalar e Configurar ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          brew install ngrok/ngrok/ngrok
          ngrok config add-authtoken $NGROK_TOKEN
          ngrok tcp 5900
